version: '3'
services:
  openssh:
    build: .
    image: ymbihq/openssh
    privileged: true
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
    command: python3 openssh.py
  closessh:
    image: ymbihq/openssh
    privileged: true
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
    command: python3 closessh.py
