version: '3'
services:
  openssh:
    build: 
      context: .
      network: host
    image: ymbihq/openssh
    privileged: true
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./:/sniffer:ro
    restart: unless-stopped
    command: /sniffer/venv/bin/python3 openssh.py
  closessh:
    image: ymbihq/openssh
    privileged: true
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./data:/data
      - ./:/sniffer:ro
    restart: unless-stopped
    command: /sniffer/venv/bin/python3 closessh.py
